;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        counsel-M-x
        delete-word
        dired-unmark-backward
        electric-newline-and-maybe-indent
        end-of-visual-line
        git-rebase-squash
        helm-projectile
        indent-for-tab-command
        jump-char-process-char
        jump-char-repeat-backward
        magit-status
        markdown-demote
        markdown-exdent-or-delete
        org-end-of-line
        ruby-end-space
        ))

(setq mc/cmds-to-run-once
      '(
        coffee-dedent-line-backspace
        duplicate-line
        haml-electric-backspace
        helm-M-x
        helm-confirm-and-exit-minibuffer
        helm-do-ag
        helm-do-ag-project-root
        kill-region
        ns-copy-including-secondary
        ns-open-file-using-panel
        org-self-insert-command
        ))
