;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-word
        helm-projectile
        magit-status
        ruby-end-space
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        helm-confirm-and-exit-minibuffer
        helm-do-ag
        ))
