;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-word
        git-rebase-squash
        helm-projectile
        magit-status
        ruby-end-space
        ))

(setq mc/cmds-to-run-once
      '(
        duplicate-line
        haml-electric-backspace
        helm-M-x
        helm-confirm-and-exit-minibuffer
        helm-do-ag
        helm-do-ag-project-root
        ns-copy-including-secondary
        ))
