#+TITLE:   Rafa's Emacs settings file
#+AUTHOR:  Rafa de Castro
#+EMAIL:   rafael@micubiculo.com
#+LANGUAGE: en
#+PROPERTY: header-args :tangle yes
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+OPTIONS: H:4 num:nil toc:t \n:nil @:t ::t |:t ^:{} -:t f:t *:t
#+OPTIONS: skip:nil d:(HIDE) tags:not-in-toc
#+TODO: SOMEDAY(s) TODO(t) INPROGRESS(i) WAITING(w@/!) NEEDSREVIEW(n@/!) | DONE(d)
#+TODO: WAITING(w@/!) HOLD(h@/!) | CANCELLED(c@/!)
#+TAGS: export(e) noexport(n)
#+STARTUP: align fold nodlcheck lognotestate content

To use this change your init file for something like

#+BEGIN_SRC
(require 'org)
(org-babel-load-file
 (expand-file-name "settings.org"
                   user-emacs-directory))
#+END_SRC

Then you will only have your org file to handle all your emacs configuration. It may sound overkill in the beginning. I'm testing this too ;)

At this moment all features are in external el files. I'm migrating from those to this dile only so there are some *load-file*s out there yet.

* Visuals

Use spaces instead of tabs

#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
#+END_SRC

I like this dark theme...

#+BEGIN_SRC emacs-lisp
(sml/setup)
(sml/apply-theme 'dark)
#+END_SRC

...but since the colors of the fonts are not that awesome this helps.

#+BEGIN_SRC emacs-lisp
(load-file "~/.emacs.d/themes/base16-emacs/base16-default-theme.el")
#+END_SRC

Disable menu and icon bar

#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
#+END_SRC

Show full path of file in status bar

#+BEGIN_SRC emacs-lisp
(setq frame-title-format '(:eval (if (buffer-file-name) (abbreviate-file-name (buffer-file-name)) "%b")))
#+END_SRC

Show line numbers

#+BEGIN_SRC emacs-lisp
(global-linum-mode t)
#+END_SRC

Paren highlight
#+BEGIN_SRC emacs-lisp
(show-paren-mode 1)
(setq show-paren-delay 0)
#+END_SRC

Font
#+BEGIN_SRC emacs-lisp
(set-face-attribute 'default nil
                    :family "M+ 1m" :height 180 :weight 'light)
#+END_SRC

Smoother scrolling with mouse. This is the only thing I still miss from Sublime text

#+BEGIN_SRC emacs-lisp
(setq mouse-wheel-follow-mouse 't)
(setq mouse-wheel-scroll-amount '(1 ((shift) . 1)))
#+END_SRC

Scrolling with keyboard before touching bottom

#+BEGIN_SRC emacs-lisp
(setq redisplay-dont-pause t
      scroll-margin 1
      scroll-step 1
      scroll-conservatively 10000
      scroll-preserve-screen-position 1)
#+END_SRC


* Minibuffer

Incremental search in minibuffer

#+BEGIN_SRC emacs-lisp
(iswitchb-mode 1)
#+END_SRC

By default arrow keys do not work in iswitchb
This can solve it

#+BEGIN_SRC emacs-lisp
(defun iswitchb-local-keys ()
  (mapc (lambda (K)
	  (let* ((key (car K)) (fun (cdr K)))
	    (define-key iswitchb-mode-map (edmacro-parse-keys key) fun)))
	'(("<right>" . iswitchb-next-match)
	  ("<left>"  . iswitchb-prev-match)
	  ("<up>"    . ignore             )
	  ("<down>"  . ignore             ))))
(add-hook 'iswitchb-define-mode-map-hook 'iswitchb-local-keys)
#+END_SRC


* TODO Not yet migrated code

This is the config files I'm yet to move to settings.org

#+BEGIN_SRC emacs-lisp
(load-file "~/.emacs.d/src/minibuffer.el")
(load-file "~/.emacs.d/src/keyboard.el")
(load-file "~/.emacs.d/src/manipulating-text.el")
(load-file "~/.emacs.d/src/windows.el")
(load-file "~/.emacs.d/src/undo.el")
(load-file "~/.emacs.d/src/selecting.el")
(load-file "~/.emacs.d/src/search.el")
(load-file "~/.emacs.d/src/open-in-external.el")

(add-hook 'before-save-hook 'delete-trailing-whitespace)

(load-file "~/.emacs.d/src/midnight.el")
(load-file "~/.emacs.d/src/backup-files.el")
(load-file "~/.emacs.d/src/spellcheck.el")

(load-file "~/.emacs.d/src/org-mode.el")

(load-file "~/.emacs.d/src/helm.el")
(defalias 'helm-buffer-match-major-mode 'helm-buffers-list--match-fn)

(load-file "~/.emacs.d/src/company-mode.el")
(load-file "~/.emacs.d/src/snippets.el")

(load-file "~/.emacs.d/src/languages/clojure.el")
(load-file "~/.emacs.d/src/languages/markdown.el")
(load-file "~/.emacs.d/src/languages/haskell.el")
(load-file "~/.emacs.d/src/languages/htmlcss.el")
(load-file "~/.emacs.d/src/languages/ruby.el")

(load-file "~/.emacs.d/src/git.el")
(load-file "~/.emacs.d/src/unmanaged.el")
(load-file "~/.emacs.d/src/dash.el")

(put 'dired-find-alternate-file 'disabled nil)

(load-file "~/.emacs.d/src/copy-rtf/copy-rtf.el")

(setq guide-key/guide-key-sequence t)
(guide-key-mode 1)

(load-file "~/.emacs.d/src/neotree.el")
#+END_SRC
